# Generated by Django 5.0.1 on 2024-01-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiyaProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('berand', models.CharField(max_length=50)),
                ('gheymat', models.IntegerField()),
                ('rang', models.IntegerField()),
                ('kod', models.IntegerField()),
                ('tedad', models.IntegerField()),
                ('size', models.IntegerField()),
                ('enter', models.IntegerField()),
            ],
        ),
    ]
