# Generated by Django 5.0.1 on 2024-01-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiyaproduct',
            name='enter',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='aiyaproduct',
            name='rang',
            field=models.CharField(max_length=50),
        ),
    ]
