# Generated by Django 5.0.1 on 2024-01-26 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_aiyaproduct_enter_alter_aiyaproduct_rang'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AiyaProduct',
            new_name='AtiyaProduct',
        ),
    ]
